export const TITLES = {
  eye_color: 'Eye color',
  birth_year: 'Birth year',
  gender: 'Gender',
  height: 'Height',
  // films: 'Films',
  mass: 'Mass',
  hair_color: 'Hair color',
  skin_color: 'Skin color',
  // homeworld: 'Home world',
  // starships: 'Star Ships',
  name: 'Name',
  // vehicles: 'Vehicles',
  // species: 'Species',
  climate: 'Climate',
  diameter: 'Diameter',
  gravity: 'Gravity',
  orbital_period: 'Orbital period',
  population: 'Population',
  // residents: 'Residents',
  rotation_period: 'Rotation period',
  surface_water: 'Surface water',
  terrain: 'Terrain',
  url: 'Url',
  // characters: 'Characters',
  opening_crawl: 'Opening crawl',
  director: 'Director',
  episode_id: 'Episode',
  // planets: 'Planets',
  producer: 'Producer',
  release_date: 'Release date',
  title: 'Title',
  average_height: 'Average height',
  average_lifespan: 'Average lifespan',
  classification: 'Classification',
  designation: 'Designation',
  eye_colors: 'Eye colors',
  hair_colors: 'Hair colors',
  language: 'Language',
  // people: 'People',
  skin_colors: 'Skin colors',
  cargo_capacity: 'Cargo capacity',
  consumables: 'Consumables',
  cost_in_credits: 'Cost in credits',
  crew: 'Crew',
  length: 'Length',
  manufacturer: 'Manufacturer',
  max_atmosphering_speed: 'Max atmosphering speed',
  model: 'Model',
  passengers: 'Passengers',
  // pilots: 'Pilots',
  vehicle_class: 'Vehicle class',
  MGLT: 'MGLT',
  hyperdrive_rating: 'Hyperdrive rating',
  starship_class: 'Starship class',
}